defaults:
  - model: dqn
  - environment: BaseEnvironment
  - writer: cometml
  - rl_agent: BasicDQNAgent
  - replayBuffer: BaseReplayBuffer
  - _self_
optimizer:
  _target_: torch.optim.RMSprop
  lr: 3e-4
trainer:
  batch_size: 199
  gamma: 0.999
  eps_start: 0.9
  eps_end: 0.05
  eps_decay: 200
  target_update: 10
  buffer_size: 10000
  n_epochs: 100
  device: auto
  override: True
  save_dir: "saved"
  seed: 1